### ISSUE TITLE
UnboundLocalError: local variable 'end_time' referenced before assignment

### ISSUE THREAD

**Issue by blueevangelion** [leonzfa/iResNet#1]
I  following all the instructions in the readme and I run into a core dumped.
I am new to caffe. I don't know what case this and how to fix it.
Aborted (core dumped)
** The resulting disparity is stored in submission_results/low_res_two_view/electro_2l.pfm
Traceback (most recent call last):
  File "test_rob.py", line 241, in <module>
    RunMethod(caffemodel, submit_dir, training_dataset_dir, dataset_name, True)
  File "test_rob.py", line 181, in RunMethod
    runtime = CalculateTime(LOG_FILE)
  File "test_rob.py", line 82, in CalculateTime
    sec = (end_time-start_time).total_seconds()
UnboundLocalError: local variable 'end_time' referenced before assignment

**Comment by leonzfa** [comment]
You can set the MAX_SIZE smaller, e.g., MAX_SIZE = 800000.
Or you can uncomment line 180 to line 190 in file test_rob.py, which is used to calculate the runtime of the algorithm.

**Comment by blueevangelion** [comment]
thx. but i ran into another problem.
while i ran sh ./make_lmdbs.sh, core dumped occured


F0613 00:30:02.507694  7514 convert_imageset_and_disparity.cpp:334] Check failed: mkdir(argv[arg_offset+2], 0744) == 0 (-1 vs. 0) mkdir ./datasets_lmdbs/FlyingThings3D_release_TRAIN_clean_lmdbfailed
*** Check failure stack trace: ***
    @     0x7fcd7fd9d5cd  google::LogMessage::Fail()
    @     0x7fcd7fd9f433  google::LogMessage::SendToLog()
    @     0x7fcd7fd9d15b  google::LogMessage::Flush()
    @     0x7fcd7fd9fe1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x405d92  main
    @     0x7fcd7e22f830  __libc_start_main
    @           0x4064c9  _start
    @              (nil)  (unknown)
Aborted (core dumped)
