### ISSUE TITLE
Aborted (core dumped) when running the test_rob.py file

### ISSUE THREAD

**Issue by firasomran** [leonzfa/iResNet#7]
Hello,
I am trying to do the evaluation stage after completing all the previous stages successfully but i am getting this error. 
Can you please advice ?
Thanks in advance 

Image size = 1032192
Executing /home/smart/Firas/iResNet-master/build/tools/caffe.bin test -model tmp/deploy.prototxt -weights model/iResNet_ROB.caffemodel -iterations 1 -gpu 0 2>&1 | tee log.txt
Aborted (core dumped)
** The resulting disparity is stored in submission_results/low_res_two_view/terrains_1l.pfm
Image size = 720896
Executing /home/smart/Firas/iResNet-master/build/tools/caffe.bin test -model tmp/deploy.prototxt -weights model/iResNet_ROB.caffemodel -iterations 1 -gpu 0 2>&1 | tee log.txt
Aborted (core dumped)
** The resulting disparity is stored in submission_results/low_res_two_view/terrains_2s.pfm
Image size = 720896
Executing /home/smart/Firas/iResNet-master/build/tools/caffe.bin test -model tmp/deploy.prototxt -weights model/iResNet_ROB.caffemodel -iterations 1 -gpu 0 2>&1 | tee log.txt
Aborted (core dumped)

**Comment by firasomran** [comment]
And after running the test commend for some time with the above mentioned (Aborted core dumped) i get the following error:

"
Traceback (most recent call last):
  File "test_rob.py", line 254, in <module>
    RunMethod(caffemodel, submit_dir, test_dataset_dir, dataset_name, False)
  File "test_rob.py", line 225, in RunMethod
    ConvertMiddlebury2014PfmToKitti2015Png(src_pfm_path, dest_png_path)
  File "/home/smart/Firas/iResNet-master/models/util_stereo.py", line 118, in ConvertMiddlebury2014PfmToKitti2015Png
    (pfm_width, pfm_height, pfm_pixels) = ReadMiddlebury2014PfmFile(src_path)
  File "/home/smart/Firas/iResNet-master/models/util_stereo.py", line 60, in ReadMiddlebury2014PfmFile
    with open(path, 'rb') as pfm_file:
IOError: [Errno 2] No such file or directory: 'submission_results/disp_0_pfm/000190_10.pfm'
"

Do you have an idea how to solve this ? 
Thanks

**Comment by LifeBeyondExpectations** [comment]
Did you solve the problem ??
